# Generated by Django 5.2.12 on 2026-04-13 17:21

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/', validators=[apps.blog.models.validate_post_image]),
        ),
    ]
